# Generated by Django 5.1.1 on 2024-09-21 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='portfolio/images')),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
